UIS-100 create CopyToClipboardButton
user-interviews/ui-design-system pull request #101
Opened 2020-12-07 15:12 UTC by jamisonordway

This adds a `CopyToClipboardButton` component which allows the user to copy some text by clicking anywhere on the button.

2020-12-07 17:22 UTC, davidmferris requested changes
Looking really good so far @jamisonordway! I have some comments for you about how we could make this more extendable and utilize some of our existing setup to simplify it a bit.

2020-12-07 17:22 UTC, davidmferris commented on scss/buttons.scss
> +.btn-outline-secondary {
Hmm it's unfortunate that we haven't added button styling to the design system yet, but you should be able to leverage Bootstrap's styling instead of needing to write it all yourself. I don't know exactly how we have it set up in the app, but I think if you look at ui_buttons.scss in the main app you should be able to cut over what you need here. The design system does have Bootstrap installed so you can get their styles by doing:
`@import '~bootstrap/scss/buttons';`

2020-12-07 17:22 UTC, davidmferris commented on src/CopyToClipboardButton/CopyToClipboardButton.jsx
> +import { CopyToClipboard as ReactCopyToClipboard } from 'react-copy-to-clipboard';
You shouldn't need the `as` here. I had to do that in the other component because there was a naming conflict with `CopyToClipboard`.

2020-12-07 17:22 UTC, davidmferris commented on scss/buttons.scss
> +  width: 351px;
For sizes and stuff, I don't think we'll actually want to define those in the design system anyways. We should allow the button to be variable width and let the rails-server app determine that depending on how we're using it.

2020-12-07 17:22 UTC, davidmferris commented on src/CopyToClipboardButton/CopyToClipboardButton.jsx
> +          className="btn-outline-secondary"
Rather than hard-coding a class here what do you think about allowing this component to accept a `variant` prop? Then we could map that to a `className`. That way this component could be used for multiple styles. Here's an [example](https://github.com/user-interviews/ui-design-system/blob/master/src/FormControlLabel/FormControlLabel.jsx#L17) of how we've done that elsewhere in the design system.

2020-12-07 17:22 UTC, davidmferris commented on src/CopyToClipboardButton/CopyToClipboardButton.jsx
> +    <div className="CopyToClipboardButton">
Now that this has been extracted from the existing `CopyToClipboard` component we should be able to plug this in there, so that'd simply be like:
```
<div className="CopyToClipboard">
  <span className="CopyToClipboard__copy-text">{copyText}</span>
  <CopyToClipboardButton copyText={copyText} trackingEvent={trackingEvent} />
</div>
```
We actually may want to consider renaming that component, but since that would be a breaking change we can hold off on that for now.

2020-12-07 17:22 UTC, davidmferris commented on src/CopyToClipboardButton/CopyToClipboardButton.jsx
> +            <span className="CopyToClipboardButton__display-text">
Could we make `displayText` undefined by default and only render this if there's a value? That way we'll be able to use this in the existing `CopyToClipboard` component.

2020-12-07 17:22 UTC, davidmferris commented on src/CopyToClipboardButton/CopyToClipboardButton.scss
> +    color: $ux-blue;
Similar to my comment above, we should be able to map this to a `variant` prop using the `classNames` package so we can allow this component to be styled differently depending on the situation.

2020-12-07 17:22 UTC, davidmferris commented on src/CopyToClipboardButton/index.js
> +export { default } from './CopyToClipboardButton';
In addition to this, you'll want to export the component in src/index.js too. That will allow us to access the component in the rails-server app.

2020-12-07 23:10 UTC, jamisonordway commented on src/Checkbox/Checkbox.jsx
> +export default function Checkbox(props) {
Completely forgot I had these `Checkbox` changes. That's really slick, thank you!

2020-12-08 00:05 UTC, davidmferris requested changes
Looking super good! I did notice when you click the button, it gets a gray background. I wonder if this would be fixed by my question to @rsaris about overriding Bootstrap defaults.

2020-12-08 00:05 UTC, davidmferris commented on src/CopyToClipboardButton/CopyToClipboardButton.jsx
> +            `btn ${props.variant}`,
This is very much a nitpick...but could we maybe check the result of `ButtonVariants[props.variant]` and pass that here (if it exists) instead? That way the component is in charge of adding "approved" classes instead of allowing the app to dictate what gets passed in here.

2020-12-08 00:05 UTC, davidmferris commented on src/CopyToClipboardButton/CopyToClipboardButton.jsx
> +                className="CopyToClipboardButton__icon"
Don't think this className is being used any longer? Can probably remove if not.

2020-12-08 00:05 UTC, davidmferris commented on stories/CopyToClipboardButton.stories.jsx
> +export const Default = () => (
Could we add a `Neutral` variant here to this file too?

2020-12-08 00:46 UTC, rroppolo commented on scss/buttons.scss
> +  color: $ux-blue;
FWIW I think it works if you put the theme in an scss import above the bootstrap ones (not sure if that is what you were doing @davidmferris) Although I mentioned to Jamison earlier I would hesitate to make that change in this branch if it is going to impact a lot of other components (for example, the btn-primary buttons in the Form stories had the wrong text color for me after adding the theme, didn't really look into why)

2020-12-08 00:50 UTC, davidmferris commented on scss/buttons.scss
> +  color: $ux-blue;
Yeah I might have just had it out of order. I would be ok to handle that in a follow up issue since it's maybe a heavy lift with unknown repercussions.

2020-12-08 01:32 UTC, rsaris commented on scss/buttons.scss
> +  color: $ux-blue;
TBH I don't think I realized that we had imported Bootstrap into this repo. With that in mind, if we have bootstrap, should we be using the mixins they provide if we are using it. For example we have:
```
.btn-outline-neutral {
  @include button-variant(transparent, $ux-gray-400);
  @include button-color($ux-gray-900);

  &:focus {
    color: $ux-gray-900;
  }
}
```
With the main repo describing:
```
@mixin button-color($color, $disabled: false) {
  color: $color;

  &:active, &:hover {
    color: $color;
  }

  // Override some very sticky Bootstrap colors
  &:not(:disabled):not(.disabled):active,
  &:not(:disabled):not(.disabled).active {
    color: $color;
  }

  @if ($disabled) {
    &:disabled {
      color: $color;
    }
  }
}
```
Which we could include in this repo.

2020-12-08 01:32 UTC, rsaris commented on scss/buttons.scss
> +  color: $ux-blue;
That said -- I'm personally OK w/ including our theming into this repo, especially if it makes us use more semantic terms here.

2020-12-08 01:49 UTC, jamisonordway commented on stories/CopyToClipboardButton.stories.jsx
> +export const Default = () => (
Would it make more sense for the neutral variant to be the default?

2020-12-08 02:46 UTC, davidmferris commented on stories/CopyToClipboardButton.stories.jsx
> +export const Default = () => (
Hmm yeah, probably makes sense that adding no additional classes/styling is the default and `Secondary` could be a variant.

2020-12-08 22:24 UTC, davidmferris commented on scss/buttons.scss
> +  color: $ux-blue;
Ok, this is maybe something we should tackle in a future effort because there's probably some things we'll want to think through and iron out. I'm hoping getting a `Button` component in here can be done sooner or later, so maybe it makes sense to handle that at that time.

2020-12-08 22:42 UTC, davidmferris requested changes
Sorry, just a couple minor things left!

2020-12-08 22:42 UTC, davidmferris commented on src/CopyToClipboard/CopyToClipboard.jsx
> +        variant={ButtonVariants.NEUTRAL}
Sorry I may have not have expressed well what I meant earlier. `ButtonVariants.NEUTRAL` or `.SECONDARY` is going to return a CSS class. I was thinking instead you'd pass `variant="neutral"` here (probably best to lowercase it so it's consistent with our other string props) and then in the component you could check like `const buttonVariant = ButtonVariants[props.variant];` and add the result of that to the `classNames` prop in that component. That way your prop check is making sure you've passed one of "neutral" or "secondary".

2020-12-08 22:42 UTC, davidmferris commented on stories/CopyToClipboardButton.stories.jsx
> +export const Default = () => (
You know what...I thought just adding a `.btn` classname would give you some bootstrap default, but when I check it out in storybook there's no border around the button. So maybe we should actually remove this `Default` for now, until we get our button/theming figured out for the other variants. Sorry about that!

![Screen Shot 2020-12-08 at 2 39 35 PM](https://user-images.githubusercontent.com/4555430/101549836-35144b00-3963-11eb-9aa6-cb5b5eab098d.png)

2020-12-08 22:42 UTC, davidmferris commented on stories/CopyToClipboardButton.stories.jsx
> +    variant={ButtonVariants.SECONDARY}
As noted above, ideally we could pass `variant="secondary"` here so that we're not passing a CSS classname as the prop.

2020-12-09 04:07 UTC, rroppolo commented on src/CopyToClipboard/CopyToClipboard.jsx
> +        variant={ButtonVariants.NEUTRAL}
Sorry if I am missing some context here but don't the propTypes already validate this @davidmferris ?
```
  variant: PropTypes.oneOf(Object.keys(ButtonVariants))
```
I feel like we use this pattern other places too

2020-12-09 04:09 UTC, rroppolo commented on src/CopyToClipboard/CopyToClipboard.jsx
> +        variant={ButtonVariants.NEUTRAL}
Ahh nm I think I see now, I didn't realize that ButtonVariants values where the css classes

2020-12-09 04:42 UTC, davidmferris commented on src/CopyToClipboard/CopyToClipboard.jsx
> +        variant={ButtonVariants.NEUTRAL}
Yeah, I was mainly hoping that we could pass it like `variant="secondary"` as opposed to `variant="btn-outline-secondary"`

2020-12-09 15:05 UTC, jamisonordway commented on src/CopyToClipboard/CopyToClipboard.jsx
> +        variant={ButtonVariants.NEUTRAL}
Ah okay I think I get it now, but let me know if I missed something. This means the ButtonVariant keys would be lowercased too, right?
```
export const ButtonVariants = {
  neutral: '',
  secondary: 'btn-outline-secondary',
};
```

2020-12-09 16:26 UTC, davidmferris commented on src/CopyToClipboard/CopyToClipboard.jsx
> +        variant={ButtonVariants.NEUTRAL}
Yep exactly! I guess the upper/lower case distinction isn't necessary, but we typically pass lowercase strings so I think it makes sense to keep it that way for consistency.

2020-12-10 00:54 UTC, davidmferris approved these changes
Yay looks great! Nice work @jamisonordway 🎉

2020-12-10 01:14 UTC, merged