[DRAFT] UIDS-122 - Add yellow color palette and update alerts colors.
user-interviews/ui-design-system pull request #124
Opened 2020-12-17 20:43 UTC by fausgaitan

WIP

2020-12-18 00:13 UTC, davidmferris requested changes
Looks great! Just a couple of small comments.

2020-12-18 00:13 UTC, davidmferris commented on scss/colors/palette.scss
> +$ux-yellow-900: #655505;
Nitpick, but could we move these below the red colors to preserve the alphabetization as well as make them ascending 100-900? Also looks like there is another $ux-yellow-100 in this file so there may be a conflict.

2020-12-18 00:13 UTC, davidmferris commented on src/Popper/Popper.scss
> +    font-weight: $font-weight-bold;
Could this use `@include font-type-30--bold;`?

2020-12-18 22:16 UTC, fausgaitan commented on scss/colors/palette.scss
> +$ux-yellow-900: #655505;
done! 71bdc1bd91254377f5ebe09384f25b7efffdad2c

2020-12-18 22:19 UTC, fausgaitan commented on src/Popper/Popper.scss
> +    font-weight: $font-weight-bold;
done! 0578ea0fa5a9cfd2d5ffcb2887a4a6644707381d

2020-12-21 19:44 UTC, davidmferris approved these changes
Looks great!

2020-12-21 19:44 UTC, merged