UIDS-70 Add Input component
user-interviews/ui-design-system pull request #71
Opened 2020-10-29 23:39 UTC by davidmferris

2020-10-30 16:47 UTC, rroppolo commented on src/InputLabel/InputLabel.jsx
>  import './InputLabel.scss';
Is InputLabel's font too small? I see it as type-20 but it looks like Faustino is using type-30?

2020-10-30 16:48 UTC, rroppolo commented on src/InputLabel/InputLabel.jsx
>  import './InputLabel.scss';
And I think the error text on the figma is type-20?

2020-10-30 16:56 UTC, rroppolo commented on src/Input/Input.scss
> +  }
I think the placeholder text is type-30 instead of type-40?

2020-10-30 20:37 UTC, fausgaitan requested changes
I added some comments.

Thanks so much for updating this!!!

2020-10-30 20:37 UTC, fausgaitan commented on src/Input/Input.scss
> +    background-color: $ux-white;
For the normal/inactive and filled states we should have a very subtle inner shadow.
![image](https://user-images.githubusercontent.com/53086200/97752390-b65dff80-1ad2-11eb-95d4-d19b574bd923.png)
This was added very recently!
`box-shadow: inset 0px 2px 2px rgba(225, 228, 232, 0.65);`

2020-10-30 20:37 UTC, fausgaitan commented on src/Input/Input.scss
> +  }
This is also a little subtle but we need to update the font size for the placeholder and the value to type-30 LIGHT. and also differentiate the colors:

![image](https://user-images.githubusercontent.com/53086200/97752768-70ee0200-1ad3-11eb-9f97-8eb775c4eef2.png)

2020-10-30 20:37 UTC, fausgaitan commented on src/Input/Input.scss
> +  }
Can we also make sure the padding / distances between the text and the input borders are 12px to the left and 8px above and below?
![image](https://user-images.githubusercontent.com/53086200/97753170-186b3480-1ad4-11eb-912c-98784b8bf26f.png)

2020-10-30 20:37 UTC, fausgaitan commented on src/FormGroup/FormGroup.scss
> +      color: $ux-red-800;
We've decided to update the label to be bold now so it should be `.font-type-30--bold` also the distance between the label and input field should be 6px.

![image](https://user-images.githubusercontent.com/53086200/97753632-d262a080-1ad4-11eb-8544-94d30af7b74d.png)

2020-10-30 20:37 UTC, fausgaitan commented on src/FormGroup/FormGroup.scss
> +      border-color: $ux-red;
we should update the error state with these colors:

![image](https://user-images.githubusercontent.com/53086200/97753994-7e0bf080-1ad5-11eb-9472-e7a4e96d26a0.png)

I've also noticed in storybook the error state the error text is different than the helper text. Can we remove the helper text when the error message shows up? and have the same font-size as the helper text? 

![image](https://user-images.githubusercontent.com/53086200/97754084-a85dae00-1ad5-11eb-8a69-c0557c6224a7.png)

2020-10-30 20:37 UTC, fausgaitan commented on src/Input/Input.scss
> +  }
we need to add a variant with both the trailing icon and the leading icon exposed:
![image](https://user-images.githubusercontent.com/53086200/97754292-07bbbe00-1ad6-11eb-91f5-00be66e6c0c7.png)

2020-10-30 21:26 UTC, davidmferris commented on src/FormGroup/FormGroup.scss
>    &__description {
Yeah I can change the name to helper-text. There are currently a few usages of the `description` prop in the app, so I'm going to keep both for now to preserve backwards compatibility, but I'll eventually remove `description` altogether.

2020-10-30 21:35 UTC, davidmferris commented on src/Input/Input.jsx
> +  onChange: PropTypes.func.isRequired,
Ah yeah, I wasn't sure if there was a case where we wouldn't want that but it sounds like there is!

2020-10-30 22:15 UTC, davidmferris commented on src/Input/Input.scss
> +    background-color: $ux-white;
Very nice!

2020-10-31 00:32 UTC, rroppolo reviewed
Looking great! I commented like two super small things but code-wise I think it looks good. I defer to Faustino to give the final 👍

2020-10-31 00:32 UTC, rroppolo commented on src/InputLabel/InputLabel.jsx
> +  tooltipText: '',
maybe undefined instead?

2020-10-31 00:32 UTC, rroppolo commented on src/InputLabel/InputLabel.scss
> +    color: $ux-gray-600;
I think this needs a font-type-30 or something so it doesn't pick up the bold from the one above?

2020-10-31 00:32 UTC, rroppolo commented on src/Input/Input.jsx
> +      )}
<img width="416" alt="Screen Shot 2020-10-30 at 5 29 39 PM" src="https://user-images.githubusercontent.com/4008333/97766845-95e37480-1ad5-11eb-8119-e2b64bc37e86.png">
I noticed this but not sure how much of a pain it is to go around the icon part...

2020-11-02 17:12 UTC, davidmferris commented on src/InputLabel/InputLabel.scss
> +    color: $ux-gray-600;
Ah yeah good catch.

2020-11-02 17:28 UTC, jojolee1996 commented
![image 3](https://user-images.githubusercontent.com/70974778/97899022-92c2d100-1ced-11eb-8dec-5d6379514bf4.png)
Minor tweak, but would you be able to change (Required) to the regular weight?

2020-11-02 17:29 UTC, davidmferris commented on src/Input/Input.jsx
> +      )}
Yeah, this is tricky. `input-group-prepend` makes this a flex box so I think in order to add the outline to the icon divs we might have to hack into the input's onfocus event and add some extra styling with javascript, which i'm a little reluctant to do. FWIW [Bootstrap](https://getbootstrap.com/docs/4.0/components/input-group/) (which provides the `input-group-prepend` class) styles their inputs so that the icon divs don't receive the focus highlighting. What do you think @fausgaitan and @jojolee1996 ?

2020-11-11 17:05 UTC, fausgaitan approved these changes

2020-11-11 17:05 UTC, fausgaitan commented on src/Input/Input.jsx
> +      )}
I like how bootstrap does it! Is it possible to add a variation for the icons to be in a container like the screenshot below? (if it's too much work, don't worry!)
![image](https://user-images.githubusercontent.com/53086200/98840756-f784d680-2425-11eb-84da-b6367f99e51c.png)

I see there's a subtle vertical shadow here, is possible to remove that for the "no container" versions?
![image](https://user-images.githubusercontent.com/53086200/98841168-7f6ae080-2426-11eb-976d-9093483bfd52.png)

2020-11-11 19:19 UTC, jojolee1996 approved these changes

2020-11-12 17:10 UTC, merged