Add Input fields documentation page
user-interviews/ui-design-system pull request #78
Opened 2020-11-18 19:43 UTC by fausgaitan

2020-12-01 12:54 UTC, fausgaitan commented on stories/Form Elements/FormGroup.stories.mdx
> +<Story name="Input Fields">
Hey @rroppolo and @davidmferris ,

I followed [these steps](https://www.learnstorybook.com/design-systems-for-developers/react/en/document/) to use MDX like I did with the Intro file, but in this case, the stories need to have this format ( <Story... )

In the original file <InputComponent> is defined like this:

```
const InputComponent = (props) => {
  const [value, setValue] = useState('');
  const handleChangeValue = (event) => setValue(event.target.value);

  return (
    <Input value={value} onChange={handleChangeValue} {...props} />
  );
};
```

Do you know how this could be translated into MDX format? I'm stuck here.  The components are not rendering for this reason (I guess).

Any help is appreciated! thanks!!

2020-12-01 16:41 UTC, davidmferris commented on stories/Form Elements/FormGroup.stories.mdx
> +<Story name="Input Fields">
I think you'll need to add an `export` to the `InputComponent` function in FormGroup.stories.jsx and then import it in this file like:
`import { InputComponent } from './FormGroup.stories';`

2020-12-02 14:11 UTC, fausgaitan commented on stories/Form Elements/FormGroup.stories.mdx
> +<Story name="Input Fields">
that worked! thanks so much! @davidmferris

2020-12-08 17:22 UTC, fausgaitan commented on stories/Form Elements/FormGroup.stories.mdx
> +  >
@davidmferris / @rroppolo 

Is it possible to add a link in the error message like this? Not sure if it's possible right now. 

![image](https://user-images.githubusercontent.com/53086200/101518535-cc2bd380-3960-11eb-8ee1-84629dcb1a04.png)

2020-12-08 17:51 UTC, rroppolo commented on stories/Form Elements/FormGroup.stories.mdx
> +  >
The errors prop on FormGroup is just validated as an object, so it looks like it does work if you pass jsx in instead of a string. For example, I just tried this test in the errors story:
```
export const WithErrors = () => (
  <FormGroup
    displayErrorText
    errors={{ test: [<div>invalid input! <a href="http://www.google.com">And a link!</a></div>] }}
```
<img width="441" alt="Screen Shot 2020-12-08 at 9 50 45 AM" src="https://user-images.githubusercontent.com/4008333/101521573-e18e0700-393a-11eb-816b-9fa788bc0c96.png">

2020-12-08 18:24 UTC, fausgaitan commented on stories/Form Elements/FormGroup.stories.mdx
> +  >
that worked! thanks!

2020-12-08 18:26 UTC, fausgaitan commented on stories/Alert.stories.mdx
> +    type={radios('Message Type', MessageTypes, MessageTypes.INFO)}
@rroppolo / @davidmferris 

Final question for this PR (hopefully) 

I added the guidelines for alerts too. And the idea is to display the different variants (success, info, warning, and error here) I updated this little part to `MessageTypes.INFO` but it's still displaying the success alert. 
I'm not sure what I'm doing wrong. 👎

2020-12-12 18:12 UTC, davidmferris requested changes
Sorry for the delay @fausgaitan. I noticed a couple of issues while testing this out in Storybook that I think we might want to address.

2020-12-12 18:12 UTC, davidmferris commented on stories/Alert.stories.jsx
> +export const onDismiss = (id) => {
Hmm this is now showing up in the Storybook sidebar. I think by default it adds an entry any time it sees `export const` in a story file. Could this be defined in the MDX file? If not we might want to do something like [this](https://storybook.js.org/docs/react/api/mdx#embedding-stories) so we can keep all the JSX in this file.

2020-12-12 18:12 UTC, davidmferris commented on stories/Alert.stories.mdx
> +import { withKnobs, radios, text } from '@storybook/addon-knobs';
I noticed the knobs aren't working on this story now. Any idea why not? You should be able to add text in the "knobs" tab and see it update live on the component.

2020-12-12 18:12 UTC, davidmferris commented on stories/Alert.stories.mdx
> +    id="1"
I think the indentation is a little off on most of the components in these two MDX files. One benefit of keeping these defined in the JSX file is that our linter will pick up those issues.

2020-12-12 18:12 UTC, davidmferris commented on stories/Form Elements/FormGroup.stories.jsx
> +export const InputComponent = (props) => {
Same issue with this export. We don't want this to show up in the Storybook sidebar I think because this should just be a wrapper component.

2020-12-12 18:15 UTC, davidmferris commented on stories/Alert.stories.jsx
> +export const onDismiss = (id) => {
Oh I just found [this](https://storybook.js.org/docs/react/api/csf#non-story-exports) as well which I think should fix this issue.

2020-12-14 18:18 UTC, jhforster commented on stories/Alert.stories.mdx
> +    id="1"
@fausgaitan do you have the linter set up? If not, might be worth having @davidmferris or @rroppolo help with that!

2020-12-14 19:40 UTC, fausgaitan commented on stories/Alert.stories.jsx
> +  excludeStories: ['onDismiss']
@davidmferris I added this line here and now the item doesn't appear in the sidebar.

![image](https://user-images.githubusercontent.com/53086200/102127266-1282a600-3e2b-11eb-92fc-6969fa926233.png)

2020-12-14 20:01 UTC, fausgaitan commented on stories/Alert.stories.mdx
> +import { withKnobs, radios, text } from '@storybook/addon-knobs';
Apparently, they are not working in the input fields section either 

I found this issue. One user says "Would be super cool to have knobs in the MDX stories!" 
Maybe I'm wrong but it looks like they've released "addon-controls"  (beta) that seems to allow the usage of knobs in mdx files?

2020-12-14 20:11 UTC, fausgaitan commented on stories/Alert.stories.mdx
> +    id="1"
I don't have it. :/ So, if any of them can help I'd appreciate it! thanks!

2020-12-14 20:17 UTC, fausgaitan commented on stories/Form Elements/FormGroup.stories.jsx
> +export const InputComponent = (props) => {
I'm not sure which item this line is adding to the sidebar?

2021-02-11 02:20 UTC, rroppolo commented
Hey @fausgaitan ! Would you mind checking out my changes to this when you get a sec? I think I kept the stories the way you had them set up but let me know or feel free to make changes if I missed anything!

2021-02-11 02:27 UTC, rroppolo commented on .eslintrc
> +        "react/jsx-indent": 0
I turned off indentation linting on the mdx files for now because it wasn't working well. Hopefully can reenable soon but didn't spend a lot of time yet, am probably missing something.

2021-02-11 02:27 UTC, rroppolo commented on stories/Alert/Alert.stories.jsx
> +  title: 'Design System/Alert',
For now I kept the name Alert vs. Alerts but probably we need to take a pass over out left-hand navigation and make sure we have a good convention in place. For now I figured we could do that in a separate PR though if that's cool. Technically the React component is called 'AlertMessage' and it lives under 'Flash/' so might want to revisit that too..

2021-02-11 02:27 UTC, rroppolo commented on stories/Alert/Alert.stories.jsx
> +import React from 'react';
This all existed btw but I moved the file into a directory so it looks like it was added

2021-02-11 02:27 UTC, rroppolo commented on stories/Form Elements/FormGroup.stories.jsx
> +export const Required = () => (
Moved around the order to better match the docs section here

2021-02-11 16:16 UTC, rsaris reviewed
This looks awesome, is there any way we can reconcile the differences in the babel imports in `yarn.lock`? Adding 3k lines to the file w/ a very small change to `package.json` feels like we did something odd. I imagine if we manually remove the `babel/core` blocks in yarn.lock it'll make it so they all use the same version of `babel/core` and we won't need to duplicate so much content there.

2021-02-16 20:57 UTC, rsaris approved these changes

2021-02-16 21:59 UTC, fausgaitan commented
LGTM @rroppolo !

2021-02-17 00:04 UTC, merged